### PR TITLE
Added a basic sphinx doc site + some readme updates

### PR DESCRIPTION
**Pull request by julianstanley**
#### Explain your changes:

I added a sphinx docs page. See https://julianstanley.github.io/rendseq/html/index.html as an example.

Just need to merge this request, + enable gh-pages in settings (on the gh-pages branch and in the docs/ folder -- @miraep8 I'll need you to go into the settings and do this enabling from your end--I think as a contributor I don't have that access)

I also added an extra CI to (1) check to make sure the documentation can build (it auto-updates based on docstrings), and (2) build and update the documentation webpage.

* Note that the documentation auto-update is commented out for now--it doesn't have permission to push currently. Maybe that'll change once this is merged? It works fine on my fork

#### Does this close any issues?

Related to #3, but no tutorial yet. 

#### PR checklist

- [X] I have written tests for my changes where needed and made sure they pass locally.

### CODE REVIEW

**Comment by julianstanley** [comment]
style check is failing because the CI is angry about all the style problems in the docs HTML files. I tried to tell it to ignore those files, not having much luck.

**Comment by miraep8** [comment]
Hey Julian,

Great!  It will be great to have the documentation up.  Thank you for getting the ball rolling on this.  :)

Small thing - in the future if you are making such a large change/decision about how we share Rendseq stuff it would be really helpful if you opened a new issue/commented on any related open issues/open a draft pull request so that we all know what you are working on and can provide feedback!  (please see the [contribution guideline](https://github.com/miraep8/rendseq/blob/main/CONTRIBUTING.md)). (I went ahead and did that for this topic here~ #32)  Sphinx is a great way to implement the documentation though, so I don't have an issue with this solution! 

As for the linting issues - Hmm in truth I am not sure that the Github repo is actually the appropriate place for many of these files. I think it would be great it you changed your .gitignore to not upload the actual build files to the Github.  In a sense - a lot of this is 'junk' that doesn't need to be explicitly shared on the Github (it distracts a bit from the main codebase) and I am worried that it might make code review harder going forward as sphinx can change a lot of files.  I think a practice followed by other OSS groups is to upload the docs, and then include instructions on how to build the docs locally and/or a build file which can be used to do this.

Anyway - this is a great start!  Changes that I will workout/add:
- Add a pipeline that allows us to build/update the docs with every change to the main branch.
-  Figure out storage and versioning control for the various doc versions! 
- Figure out how to store and serve all our documentation files!
-  Add instructions for how to add to the docs/how to work with Sphinx.

**Comment by julianstanley** [comment]
> As for the linting issues - Hmm in truth I am not sure that the Github repo is actually the appropriate place for many of these files. I think it would be great it you changed your .gitignore to not upload the actual build files to the Github.  In a sense - a lot of this is 'junk' that doesn't need to be explicitly shared on the Github (it distracts a bit from the main codebase) and I am worried that it might make code review harder going forward as sphinx can change a lot of files.  I think a practice followed by other OSS groups is to upload the files/code needed to make the documentation files - ie the .rst files, code that executes Sphinx etc, and then include instructions on how to build the docs locally and/or a build file which can be used to do this.

Linting works now. 

It is standard practice to host Sphinx documentation files in some respect, e.g. see BioPython. 

Gh-pages is a common solution. 

For cleanliness, we could exclude those build files from main and only have them on a gh-pages branch. 

Requiring users to download the repo and build docs seems kinda unnecessary when they can be easily hosted online, right? 


> - Add a pipeline that allows us to build/update the docs with every change to the main branch.

I included this in this pull request. 

> -  Figure out storage and versioning control for the various doc versions! 

Sphinx has this built in with the sphinx-multiversion extension. But rendseq doesn't have multiple versions yet. 

> -  Add instructions for how to add to the docs/how to work with Sphinx. 

Sphinx has a lot of this--you just edit the main rst file and run build html to build. But happy to add that somewhere if you'd like

**Comment by miraep8** [comment]
Hey!  Thanks for the quick response/thoughts!  It seems some of the things I brought up were a bit unclear, so let me clarify a few things:
 
> I think it is standard practice to host Sphinx documentation files in some respect, e.g. see BioPython.
> 
> For cleanliness, we could exclude those build files from main and only have them on a gh-pages branch.
>

Yes!  I think my main point here was that we probably don't need most of the files generated by the build - ie most of the .html files, .woff files, .css files etc on github! I totally agree that it would be necessary to have the other doc files in the github (ie .rst files etc) though so that everyone can contribute to it/edit it! :) I just don't think that the output of the build files need to be there :) eg, for example I looked at the Biopython example you mentioned and it seemed like they didn't keep a lot of such files there - with the exception of templates/specialized .css additions?

> Requiring users to download the repo and build docs seems kinda unnecessary when they can be easily hosted online, right?

Of course we would host the documentation online :) My comment on having instructions of how to build the docs locally was more targeted at contributors!  ie - you have made some changes to the doc - this is how you can view them locally!  For example the repo you mentioned Biopython [has some instructions](https://github.com/biopython/biopython/tree/master/Doc) for how to do this!  I agree, its not necessarily a super mission critical addition - just something I could imagine new contributors finding useful - but totally something we can add in later!  

> 
> > * Add a pipeline that allows us to build/update the docs with every change to the main branch.
> 
> I included this in this pull request.

Great!  I saw that! :)  Thanks again! -What I was getting at here wasn't just running the Sphinx build with changes to the main branch - (though its great we have that!), but taking the output of those files and hosting them! In particular this was just kind of a note to myself to include documentation publishing with a `publish` workflow!  :) Was just meant to be an addition to what you already had, not a replacement! 

> Sphinx has this built in with the sphinx-multiversion extension. But rendseq doesn't have multiple versions yet.

Ah great! :) Then maybe this is the solution we will use. rendseq doesn't have multiple versions yet, but I think that is the long term plan - just wanted to make sure that we have a forward looking documentation software that can handle this for us. Thanks for pointing out the sphinx-multiversion extension, I will check it out more!

> > * Add instructions for how to add to the docs/how to work with Sphinx.
> 
> Sphinx has a lot of this--you just edit the main rst file and run build html to build. But happy to add that somewhere if you'd like

Yes - no worries - I didn't have any plans to re-write the Sphinx docs!  I simple thought it would be worth while we are laying down some of the guidelines with respect to documentation if we established some general guidelines for how to contribute to documentation/explain what is going on! For example BioPython has a [README.rst ](https://github.com/biopython/biopython/tree/master/Doc) that also explains how to do that!  In addition I think there can be a lot more to documentation than what Sphinx can auto-format can scrape together for us - for example in an ideal world I would also love to have the tutorials we build integrated in some way!  And maybe some more high level descriptions of what the code does/why!  And I think it is useful to share guidelines for how to contribute to these things - as well as for us to think about how we want to format these things! 

> Gh-pages is a common solution when folks don't have an external hosting platform.

Sure, I am potentially open to using Gh-pages!  I kinda liked the idea of using [Read The Docs](https://readthedocs.org/) though!  The idea here being that then our documentation would live with lots of other pre-existing documentation and would be easier to find (and my understanding is that it is also pretty easy to interface with Github!)!  Plus it is also free! (Though I also have hopes that we can secure our own domain and have our documentation files live there in addition at some point in the future!)  Though if you have a strong reason that we should use Github pages instead I would love to hear it!

Anyway - like I said before - really appreciate you kicking off the discussion with documentation!  I think it is a really important discussion to have!  I just think it is worth taking some time to think about how we want to things to avoid the need to refactor in the future :) Happy to continue the discussion here, or on #32 - would also be happy to hear your thoughts on some of the above. :)

**Comment by julianstanley** [comment]
> Hey!  Thanks for the quick response/thoughts!  

Likewise! Thanks for clarifying all this

> Great!  I saw that! :)  Thanks again! -What I was getting at here wasn't just running the Sphinx build with changes to the main branch - (though its great we have that!), but taking the output of those files and hosting them! In particular this was just kind of a note to myself to include documentation publishing with a `publish` workflow!  :) Was just meant to be an addition to what you already had, not a replacement! 

Ah nice--yeah the workflow I included publishes, but to GitHub pages. 

> Yes - no worries - I didn't have any plans to re-write the Sphinx docs!  I simple thought it would be worth while we are laying down some of the guidelines with respect to documentation if we established some general guidelines for how to contribute to documentation/explain what is going on! For example BioPython has a [README.rst ](https://github.com/biopython/biopython/tree/master/Doc) that also explains how to do that!  In addition I think there can be a lot more to documentation than what Sphinx can auto-format can scrape together for us - for example in an ideal world I would also love to have the tutorials we build integrated in some way!  And maybe some more high level descriptions of what the code does/why!  And I think it is useful to share guidelines for how to contribute to these things - as well as for us to think about how we want to format these things! 

Yeah, I also think it would be great to host tutorials in the same place as docs--that seems doable. 

And note that this PR also includes a readme update--I can add some doc build instructions there. 

> I kinda liked the idea of using [Read The Docs](https://readthedocs.org/) though!  The idea here being that then our documentation would live with lots of other pre-existing documentation and would be easier to find (and my understanding is that it is also pretty easy to interface with Github!)!  Plus it is also free! (Though I also have hopes that we can secure our own domain and have our documentation files live there in addition at some point in the future!)  Though if you have a strong reason that we should use Github pages instead I would love to hear it!

That sounds awesome--I didn't know that was an option! I've always used the read the docs theme to Sphinx, so obv a fan of their platform. The biggest advantage of pages is to be able to automatically update docs--but I bet rtd has some option to do that too. 


> Anyway - like I said before - really appreciate you kicking off the discussion with documentation!  I think it is a really important discussion to have!  

Totally--I agree that it's important to talk about, hopefully my directness on GitHub doesn't suggest otherwise. I rarely expect PRs to be the right thing off the bat, just easier for me to submit things that work and go from there 😅 especially quick stuff like Sphinx. 




Okay, so I can make those readme changes and figure out the rtd stuff, or I can leave it if you'd prefer (you should also be able to commit to this pull request). Just lmk

**Comment by miraep8** [comment]
Great!  I am glad you also like the idea of the ReadTheDocs option! It honestly seems like it will dovetail really well with the Sphinx setup you already have here! :)  I was checking out their tutorial and it looked like there were one or two things I might need to set up as the owner of the repo, I will go ahead and make an account/take care of the permissions!  I think on your end it might be useful to remove some of those extra files from this commit (can check out their [example repo](https://github.com/readthedocs/tutorial-template/) for sort of the minimal files needed for RTD to make the site).  Then we might basically be ready to go?

**Comment by miraep8** [comment]
We are [now on ReadTheDocs](https://rendseq.readthedocs.io/en/latest/). Just a place-holder now but once we merge this branch and have the index.rst file in the docs/ folder I think we can make sure they sync/everything looks good.

**Comment by miraep8** [comment]
Just kidding - I think we will need to actually add the readthedacs.yml file and also a conf.py file. I will take a stab at implementing those when I have some more time and will try to merge them with this branch

**Comment by julianstanley** [comment]
> I think on your end it might be useful to remove some of those extra files from this commit (can check out their [example repo](https://github.com/readthedocs/tutorial-template/) for sort of the minimal files needed for RTD to make the site).

All set with this, I think! Followed the structure from that tutorial template.

> Just kidding - I think we will need to actually add the readthedacs.yml file and also a conf.py file. I will take a stab at implementing those when I have some more time and will try to merge them with this branch

I went ahead and did that too in order to get this all setup on my fork.

Initial docs look like this on my end: https://julianstanley-rendseq-fork.readthedocs.io/en/latest/

-----------

So I think it's all in your court now to make sure this works on your readthedocs admin side--let me know if there's anything else you want updated from my end!

**Comment by miraep8** [comment]
Great!  Thanks Julian! I think I will go ahead and merge this branch then can make any other changes that are needed through a future PR.  Thanks a bunch - the preview on your site looks good!

**Pull request merged**
