### PR TITLE
Just a quick test for #29 and #12

### PR DESCRIPTION
**Pull request by julianstanley**
#### Explain your changes:

Just wrote a test to make sure #12 was resolved. 

#### Does this close any issues?

No

#### Any comments?  Anything in particular you need feedback on?

N/A

#### PR checklist

- [X] I have written tests for my changes where needed and made sure they pass locally.

### CODE REVIEW

**Comment by julianstanley** [comment]
Very interesting that this fails on 3.8 but not 3.7 or 3.9. It is intuitive that the calc_thresh score would change after z-score trimming, though. But it's weird that it didn't fail in #29? I'll change that 8.3 to a 5.2 and see how it looks

image

**Comment by julianstanley** [comment]
Okay I re-ran the CI and now everything works well, even without any changes. @miraep8 is there any stochasticity in the threshold measurement that I'm missing that could've caused that glitch?

**Comment by miraep8** [comment]
Hmmmm, well the change I made to trim the zscores should only affect hmm_peaks, as I don't actually touch the underlying z_scores at all....

**Comment by julianstanley** [comment]
That makes sense. For my tests, I did generate a normal distribution of Z-scores, so that's a stochastic component. I wonder if that's what did it? Anyways, will keep a lookout for tests failing in the future--if it is that Z-score generation, then it must only happen very rarely and can be fixed by just re-running CI.

**Comment by miraep8** [comment]
I imagine that was the case?  Though I am surprised by how much it moved the distribution ... ie to 5.2.... but yes - agreed lets keep a look out!

**Pull request merged**
