### PR TITLE
Add pytests to CI

### PR DESCRIPTION
**Pull request by miraep8**
Trying out the minimal Ubuntu version again.

### CODE REVIEW

**Comment by miraep8** [comment]
Need to update requirements.txt

**Comment by miraep8** [comment]
Nice, now will add in other OSs

**Comment by miraep8** [comment]
🎉

**Review by julianstanley — APPROVED** [review]
This looks fantastic to me!

It's good to go as is, but one thing to think about: my R packages had separate dependencies for users and for folks trying to test the package. 

It looks like this pull adds a ton of requirements that are only there for testing. But I think that means any old user installing this on pip is now going to have to install a ton of packages. 

Is there an equivalent for python packages to specify "optional testing" packages?

**Comment by miraep8** [comment]
Oooooo, Good question.  I think there is a way to specify "dev" requirements vs "usage" requirements.  Will check it out, good suggestion!

**Pull request merged**
